version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scm
    ports:
      - "3307:3306"

  springboot:
    build: .
    container_name: scm_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scm
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - mysql
