services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scm
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "16.16.24.173:3307"]
      interval: 10s
      timeout: 5s
      retries: 3

    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: scm_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scm
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data:
